### ISSUE TITLE
crypto.js 报错了

### ISSUE THREAD

**Issue by seekwe** [nondanee/UnblockNeteaseMusic#1]
是否解密问题了

node app.js -p 1630
```js
Server running @ http://0.0.0.0:1630
Proxy HTTP request for: http://music.163.com
crypto.js:170
  var ret = this._handle.update(data, inputEncoding);
                         ^

TypeError: Bad input string
    at Decipheriv.update (crypto.js:170:26)
    at decrypt (/www/wwwroot/qt/UnblockNeteaseMusic/crypto.js:9:22)
    at decryptEapi (/www/wwwroot/qt/UnblockNeteaseMusic/crypto.js:22:9)
    at IncomingMessage.<anonymous> (/www/wwwroot/qt/UnblockNeteaseMusic/proxy.js:86:14)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by nondanee** [comment]
哪一个平台的客户端？

**Comment by seekwe** [comment]
linux下启动，win下使用代码

**Comment by nondanee** [comment]
用pac自动代理吗？
查一下linux下的node版本
release里有可执行文件也可以运行试试看
我用最新版的windows客户端测过了没问题的

**Comment by seekwe** [comment]
node v8.11.2 
这个不行?
还是说因为我windows客户端不是最新的?

**Comment by nondanee** [comment]
Node8可以恩，客户端版本是多少嘞？

**Comment by nondanee** [comment]
找了2.0.3版试了下，是因为旧版加密参数末尾有填充`%0...`，已处理

**Comment by seekwe** [comment]
谢谢啦 O(∩_∩)O哈哈~ (...我用的居然是2.0.2)
