### ISSUE TITLE
无法长期运行

### ISSUE THREAD

**Issue by SidW** [nondanee/UnblockNeteaseMusic#118]
程序似乎在运行一段时间后 会出现报错 之后停止服务。 查看log发现如下异常
```
(node:26105) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of null
    at Object.close (/home/sid/ws/UnblockNeteaseMusic/server.js:109:19)
    at /home/sid/ws/UnblockNeteaseMusic/server.js:34:29
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:26105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2340)
```
平台是Azure上的Ubuntu
使用node app.js 直接运行

**Comment by onewayticket255** [comment]
我也会出现这个log，然后server停止（看log似乎报错一次还是正常运行，多次后server就会终止）。

加个判断`if(ctx.res.socket)`可以解决，具体细节原因不知。

https://github.com/nondanee/UnblockNeteaseMusic/blob/b3c84711b29a5a531bab3b34faed0d0440b7edb9/server.js#L109
