### ISSUE TITLE
搜索被和谐的歌手时有未处理的异常

### ISSUE THREAD

**Issue by mu-yu** [nondanee/UnblockNeteaseMusic#12]
```
(node:4460) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'songs' of undefined
    at F:\github\UnblockNeteaseMusic\proxy.js:284:25
    at new Promise (<anonymous>)
    at bodyHook (F:\github\UnblockNeteaseMusic\proxy.js:217:9)
    at F:\github\UnblockNeteaseMusic\proxy.js:128:9
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:4460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

**Comment by nondanee** [comment]
不会是发麻麻吧😂

**Comment by mu-yu** [comment]
被你猜中了:joy:

**Comment by nondanee** [comment]
hhh已修复😂😂😂
