### ISSUE TITLE
crash on zlib.js:411

### ISSUE THREAD

**Issue by ludacriz** [nondanee/UnblockNeteaseMusic#145]
不知道什么原因，但是`zlib.unzipSync`的确会throw exception，所以不妨catch忽略之
作者辛苦

```
zlib.js:411
      throw error;

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
    at processChunkSync (zlib.js:403:12)
    at zlibBufferSync (zlib.js:148:12)
    at Object.syncBufferWrapper [as unzipSync] (zlib.js:724:14)
    at IncomingMessage.connect.on.on (/usr/src/app/request.js:81:104)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by nondanee** [comment]
好的

**Comment by xtlsoft** [comment]
And the docker image hasn't been updated :-)
