### ISSUE TITLE
BUG反馈 无法运行

### ISSUE THREAD

**Issue by 1715173329** [nondanee/UnblockNeteaseMusic#174]
运行报错：
```bash
> node /usr/share/unblockneteasemusic/app.js -p 5000

{ Error: connect ECONNREFUSED :::443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::',
  port: 443 }
```

尝试指定网易云音乐服务器IP也没有作用。
Node.JS版本：v8.10.0，架构：mipsle / Newifi D2

**Comment by 1715173329** [comment]
疑似IP遭到阻断。重新拨号后已解决此问题。

**Comment by nondanee** [comment]
是 httpdns 阶段出的错，与指定网易云服务器 IP 无关
https://github.com/nondanee/UnblockNeteaseMusic/blob/0a69671f1595336dc17348a613c1409aefe3cfef/app.js#L70-L71
如果 https 有问题可以改成 http

解决了就好

**Comment by 1715173329** [comment]
好的，感谢您的回复！
