### ISSUE TITLE
node app.js启动失败

### ISSUE THREAD

**Issue by wangmingdong** [nondanee/UnblockNeteaseMusic#187]
Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
    at Promise.all.then.result (/usr/lib/node_modules/@nondanee/unblockneteasemusic/app.js:79:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at emitErrorNT (net.js:1297:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by nondanee** [comment]
遇到问题先自己查一下

端口被占了，换个端口就行了
