### ISSUE TITLE
Ubuntu部署出错

### ISSUE THREAD

**Issue by Fretory** [nondanee/UnblockNeteaseMusic#189]
/home/ubuntu/UnblockNeteaseMusic/app.js:75
        let extra = Array.from(new Set(result.reduce((merged, array) => merged.c                   oncat(array), [])))
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup                   ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

阿里云&&aws 运行均出错

系统:ubuntu 16.04

**Comment by nondanee** [comment]
node 版本太低了，要求 node 6+
