### ISSUE TITLE
不支持 ECC CA 证书

### ISSUE THREAD

**Issue by ZeroClover** [nondanee/UnblockNeteaseMusic#290]
将 `server.crt` 和 `server.key` 替换为 ECC CA 证书后，运行出现如下错误：

```
_tls_common.js:131
      c.context.setCert(cert);
                ^

Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:131:17)
    at Server.setSecureContext (_tls_wrap.js:1155:27)
    at Server (_tls_wrap.js:1033:8)
    at new Server (https.js:65:14)
    at Object.createServer (https.js:89:10)
    at Object.<anonymous> (/path/to/UnblockNeteaseMusic/server.js:172:26)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

使用 RSA CA 证书正常。

**Comment by nondanee** [comment]
CA 证书是 `ca.crt` 这个文件
`server.crt` 和 `server.key` 分别是服务器证书和服务器私钥
这个报错说你的证书不是 pem 格式的

不知道 ECC 证书是不是就是用 ECC 私钥的意思
我这样试了下
```
# 生成 CA 私钥
# openssl genrsa -out ca.key 2048 (这是 RSA 的)
openssl ecparam -out ca.key -name prime256v1 -genkey

# 生成 CA 证书 ("YOURNAME" 处填上你自己的名字)
openssl req -x509 -new -nodes -key ca.key -sha256 -days 1825 -out ca.crt -subj "/C=CN/CN=UnblockNeteaseMusic Root CA/O=YOURNAME"

# 生成服务器私钥
# openssl genrsa -out server.key 2048 (这是 RSA 的)
openssl ecparam -out server.key -name prime256v1 -genkey

# 生成证书签发请求
openssl req -new -sha256 -key server.key -out server.csr -subj "/C=CN/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=IT Dept./CN=*.music.163.com"

# 使用 CA 签发服务器证书
openssl x509 -req -extfile <(printf "subjectAltName=DNS:music.163.com,DNS:*.music.163.com") -days 365 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt
```
并没有问题
