### ISSUE TITLE
Error: socket hang up 

### ISSUE THREAD

**Issue by shzxm** [nondanee/UnblockNeteaseMusic#315]
{ Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1137:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',
  path: null,
  host: '59.111.181.38',
  port: 443,
  localAddress: undefined }

版本
commit c727245b8de201b91ae859c6ae1412c77ef25cf0 (HEAD -> master, tag: v0.22.1, origin/master, origin/HEAD)
Author: nondanee <iminezn5656@outlook.com>
Date:   Mon Nov 18 01:00:02 2019 +0800

**Comment by nondanee** [comment]
之前版本有问题吗？

**Comment by shzxm** [comment]
大概上次升级1个多月前了.上一个今天发现不能用.所以升级了

**Comment by nondanee** [comment]
那就把 `app.js` reset 到 https://github.com/nondanee/UnblockNeteaseMusic/commit/ddedd270de17bce2c5387ef8a54b5bd51ebe2584 之前的版本

**Comment by shzxm** [comment]
好的.我试一下
