### ISSUE TITLE
node app.js 报错

### ISSUE THREAD

**Issue by Hedilict** [nondanee/UnblockNeteaseMusic#395]
node app.js 
/root/UnblockNeteaseMusic/src/cli.js:5
        program: (information = {}) => {
                              ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/UnblockNeteaseMusic/src/app.js:4:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by nondanee** [comment]
node 版本太低了
