### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xiaoming1112** [nondanee/UnblockNeteaseMusic#408]
{ Error: connect EACCES 59.111.181.38:443 - Local (undefined:undefined)
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at internalConnect (net.js:976:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:283:19)
    at net.js:1074:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'connect',
  address: '59.111.181.38',
  port: 443 }

**Comment by nondanee** [comment]
如何复现？前因后果，使用方式 (源码/npx/docker)，代理方式及代理日志 (系统代理/surge/clash/.....) ，启动(守护)方式 (systemd/pm2/...)，网络环境等等
`Local (undefined:undefined)` 这个说明了什么？

59.111.181.38 是硬编码的 music.httpdns.c.163.com 地址，我查了下还是有解析的
https://www.boce.com/tool?url=music.httpdns.c.163.com&type=get
