### ISSUE TITLE
Windows无法使用？

### ISSUE THREAD

**Issue by JackieQin** [nondanee/UnblockNeteaseMusic#600]
报错信息：
C:\Users\Jackie PC>npx @nondanee/unblockneteasemusic
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at C:\Users\Jackie PC\node_modules\@nondanee\unblockneteasemusic\src\app.js:83:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080
}

**Comment by ryanchenandsyy** [comment]
用管理员模式运行再试

**Comment by dsl14122** [comment]
默认端口号被占用？
