### ISSUE TITLE
unable to connect to netease

### ISSUE THREAD

**Issue by frankyifei** [nondanee/UnblockNeteaseMusic#638]
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:312:28)
    at TLSSocket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ECONNRESET',
  path: null,
  host: '59.111.179.213',
  port: 443,
  localAddress: undefined

**Comment by stepbystepcode** [comment]
Me too. How to solve it?
