### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by wth951** [nondanee/UnblockNeteaseMusic#660]
node app.js命令启动报错，如下：
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

目前手上win10，nas（docker）都报这个错误，求大佬指教

**Comment by felixzou83** [comment]
群晖docker也是一样的的问题，求解：
Error: unable to verify the first certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
at TLSSocket.emit (events.js:223:5)
at TLSSocket._finishInit (_tls_wrap.js:794:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) { 
code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' 

感谢

**Comment by Cirn09** [comment]
不一样但原理应该类似的报错
```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: music.httpdns.c.163.com. is not in the cert's altnames: DNS:*.music.163.com, DNS:music.163.com
    at Object.checkServerIdentity (tls.js:297:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  reason: "Host: music.httpdns.c.163.com. is not in the cert's altnames: DNS:*.music.163.com, DNS:music.163.com",
  host: 'music.httpdns.c.163.com',
...
```

**Comment by if1y** [comment]
Linux 脚本，同样问题，首次启动没有问题

```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12) {
  code: 'CERT_HAS_EXPIRED'
}
```
