### ISSUE TITLE
请问是证书过期了么？

### ISSUE THREAD

**Issue by eipip1e0** [nondanee/UnblockNeteaseMusic#662]
前两天还好好的，今天突然报错。应该咋办呀？

Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  code: 'CERT_HAS_EXPIRED'
}

**Comment by JiayangZhou** [comment]
一样呀，我也是今天收到的错误提示，蹲一个，Mac上显示证书(UnblockNeteaseMusic Root CA)还是被信任的。

**Comment by OranHW** [comment]
我这里也是！

**Comment by Herrengit** [comment]
一样的问题

**Comment by eipip1e0** [comment]
手机端的unblockMusicPro_xposed也一样，显示证书过期了

**Comment by OranHW** [comment]
是网易云自己当机了吧 我手机也打不开music.163.com

**Comment by dteen** [comment]
{ Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1088:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:666:8) code: 'CERT_HAS_EXPIRED' }

**Comment by galen1119** [comment]
同样的问题

**Comment by czy1238677** [comment]
windows端同样的问题

**Comment by leonsong09** [comment]
windows 同样的问题 今天证书过期了

**Comment by njusilvaz** [comment]
同样的问题~希望能更新下证书

**Comment by sujundada** [comment]
昨天都还好好的   今天就不行了 该怎么解决

**Comment by laitanzhou** [comment]
docker也是

**Comment by zwbdmm** [comment]
我这里也是 cert_has_expired

**Comment by ActiveSoul8231** [comment]
我也是相同情况哈

**Comment by andylizi** [comment]
b8d5f4b4fe59cef9c021b99f3cf2606d99fa4790 已经修了，但还没发新版本。暂时自己 pull 一下 master 来用吧。

**Comment by JiayangZhou** [comment]
可以用了 谢谢！

**Comment by zwbdmm** [comment]
@andylizi 感谢 git pull了master 已经重新可以用了

**Comment by dteen** [comment]
at JSON.parse (<anonymous>)
    at read.then.body (/root/UnblockNeteaseMusic/src/request.js:89:64)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by 955s** [comment]
> @andylizi 感谢 git pull了master 已经重新可以用了

分支貌似比这个要晚

**Comment by WangXiaopai595** [comment]
一样的问题，证书失效

**Comment by eipip1e0** [comment]
感谢各位，已经可以用了

**Comment by if1y** [comment]
> [b8d5f4b](https://github.com/nondanee/UnblockNeteaseMusic/commit/b8d5f4b4fe59cef9c021b99f3cf2606d99fa4790) 已经修了，但还没发新版本。暂时自己 pull 一下 master 来用吧。

Android 使用 UnblockMusic Pro 替换文件后问题依旧

**Comment by duhd1993** [comment]
这是网易的证书过期，这么大公司，肯定很快会修复的（大概

**Comment by UmbraCi** [comment]
> 这是网易的证书过期，这么大公司，肯定很快会修复的（大概

不是项目的CA证书过期了吗

**Comment by UmbraCi** [comment]
> [b8d5f4b](https://github.com/nondanee/UnblockNeteaseMusic/commit/b8d5f4b4fe59cef9c021b99f3cf2606d99fa4790) 已经修了，但还没发新版本。暂时自己 pull 一下 master 来用吧。

npx: 1 安装成功，用时 2.2 秒
Error: certificate has expired
还是不行，用的master分支
执行的命令是：npx @nondanee/unblockneteasemusic

**Comment by duhd1993** [comment]
> > 这是网易的证书过期，这么大公司，肯定很快会修复的（大概
> 
> 不是项目的CA证书过期了吗

不是

**Comment by duhd1993** [comment]
> > [b8d5f4b](https://github.com/nondanee/UnblockNeteaseMusic/commit/b8d5f4b4fe59cef9c021b99f3cf2606d99fa4790) 已经修了，但还没发新版本。暂时自己 pull 一下 master 来用吧。
> 
> npx: 1 安装成功，用时 2.2 秒
> Error: certificate has expired
> 还是不行，用的master分支
> 执行的命令是：npx @nondanee/unblockneteasemusic

npx是从npmjs下载的，不是从github。可以npx github:nondanee/UnblockNeteaseMusic

**Comment by Zero-Kiryu** [comment]
大佬V5，修复及时，感谢
