### ISSUE TITLE
昨天可以正常使用今天报错

### ISSUE THREAD

**Issue by nebulapriest** [nondanee/UnblockNeteaseMusic#665]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\燚\app.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by nebulapriest** [comment]
大佬修复的是真的快

**Comment by 955s** [comment]
> 大佬修复的是真的快

我用了最新提交的app.js还是不错。

**Comment by Rasmus-cao** [comment]
> internal / modules / cjs / loader.js：883
> throw err;
> ^
> 
> 错误：无法在'
> Function.Module._resolveFilename（internal / modules / cjs / loader.js：880：15）处找到模块'C：\ Users \燚\ app.js' [[90m at Function.Module._resolveFilename（internal / modules / cjs / loader.js：880：15）
> 。] Module._load（internal / modules / cjs / loader.js：725：27）。[39m
> ... [90m at Function.executeUserEntryPoint [as runMain]（internal / modules / run_main.js：72：12）。[39m
> ... [内部/主/run_main_module.js:17:47处90m。[39m {
> 代码： [32m'MODULE_NOT_FOUND'。[39m，
> requireStack：[]
> }



> internal/modules/cjs/loader.js:883
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\燚\app.js'
> �[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)�[39m
> �[90m at Function.Module._load (internal/modules/cjs/loader.js:725:27)�[39m
> �[90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)�[39m
> �[90m at internal/main/run_main_module.js:17:47�[39m {
> code: �[32m'MODULE_NOT_FOUND'�[39m,
> requireStack: []
> }



> internal/modules/cjs/loader.js:883
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\燚\app.js'
> �[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)�[39m
> �[90m at Function.Module._load (internal/modules/cjs/loader.js:725:27)�[39m
> �[90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)�[39m
> �[90m at internal/main/run_main_module.js:17:47�[39m {
> code: �[32m'MODULE_NOT_FOUND'�[39m,
> requireStack: []
> }

我也出现了这个问题  该咋办？  而且bat文件还一闪而过

**Comment by Rasmus-cao** [comment]
internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module 'C:\UnblockNeteaseMusic-master\app.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:742:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}   我也出现了这个问题  该咋办啊？   我之前是将txt改成bat文件使用的   今天bat文件总是一闪而过   加了pause命令才看到以上错误命令

**Comment by llllcccjjj** [comment]
![image](https://user-images.githubusercontent.com/70000656/102982770-0b077f00-4546-11eb-8463-425f0eefdd36.png)
我的证书更新几次了还是不行

**Comment by cyao2q** [comment]
证书过期 是什么证书过期啊 打不开了

**Comment by llllcccjjj** [comment]
> 证书过期 是什么证书过期啊 打不开了

重新下载这个项目 跑一下就可以了 已解决

**Comment by caliban511** [comment]
---
下载了最新的app.js并覆盖过去，还是闪退。我用的是node app.js，然后改网易云代理的方式。
--------------------------
重启电脑以后好了，，，奇怪，应该不需要重启的才对啊，，，
总之感谢大佬修复。。。
