### ISSUE TITLE
Mac 下报错 `ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH` 和 `ERR_OSSL_EVP_BAD_DECRYPT`

### ISSUE THREAD

**Issue by pea3nut** [nondanee/UnblockNeteaseMusic#722]
配置好 host、CLI Server、证书后打开网易云后发现歌曲依旧是灰的，CLI 输出有报错

Mac系统，地点新加坡

CLI 输出

```
C02F72G3MD6R:~ peadarliu$ npx @nondanee/unblockneteasemusic -p 80:443 -f 103.126.92.132
npx: installed 1 in 1.024s
HTTP Server running @ http://0.0.0.0:80
HTTPS Server running @ http://0.0.0.0:443
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at decrypt (/Users/peadarliu/.npm/_npx/4413/lib/node_modules/@nondanee/unblockneteasemusic/src/crypto.js:12:58)
    at Object.decrypt (/Users/peadarliu/.npm/_npx/4413/lib/node_modules/@nondanee/unblockneteasemusic/src/crypto.js:23:22)
    at /Users/peadarliu/.npm/_npx/4413/lib/node_modules/@nondanee/unblockneteasemusic/src/hook.js:154:53
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'wrong final block length',
  code: 'ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH'
} https://music.163.com/eapi/batch
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.final (internal/crypto/cipher.js:174:29)
    at decrypt (/Users/peadarliu/.npm/_npx/4413/lib/node_modules/@nondanee/unblockneteasemusic/src/crypto.js:12:58)
    at Object.decrypt (/Users/peadarliu/.npm/_npx/4413/lib/node_modules/@nondanee/unblockneteasemusic/src/crypto.js:23:22)
    at /Users/peadarliu/.npm/_npx/4413/lib/node_modules/@nondanee/unblockneteasemusic/src/hook.js:154:53
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
} https://music.163.com/eapi/batch
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
MITM > music.163.com (ssl)
```

Host 文件内容：

```
C02F72G3MD6R:~ peadarliu$ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
127.0.0.1	music.163.com
127.0.0.1	interface.music.163.com
C02F72G3MD6R:~ peadarliu$
```

证书配置：

<img width="899" alt="image" src="https://user-images.githubusercontent.com/13781420/111896069-f73ebc80-8a51-11eb-81d6-61b6f3a1138c.png">

网易云及Mac版本：

<img width="396" alt="image" src="https://user-images.githubusercontent.com/13781420/111896043-c494c400-8a51-11eb-814f-553f5e403265.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/13781420/111896046-cb233b80-8a51-11eb-8e24-4eb95a68f612.png">

**Comment by pea3nut** [comment]
重启后就好了。。。猜测是需要把证书窗口关了才会生效
