### ISSUE TITLE
PC上本地运行，node app.js 无法启动

### ISSUE THREAD

**Issue by yunzhongxicao** [nondanee/UnblockNeteaseMusic#767]
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80
}

**Comment by yunzhongxicao** [comment]
启动方式更换为npx @nondanee/unblockneteasemusic 可以启动，想问下是啥原因呢

**Comment by layris3** [comment]
does `node app.js -p 8080` work?

**Comment by KiriTowaha** [comment]
我也是，node app.js -p 8080 都不行。nodejs 版本 14.17.3 LTS 和 16.5都不行
![image](https://user-images.githubusercontent.com/64723622/126069623-6eb6372a-c333-4689-adb7-9321668c2a58.png)
內面的ip地址是網易的

**Comment by KiriTowaha** [comment]
但是我在另一台電腦沒有這個問題

**Comment by syymo** [comment]
> does `node app.js -p 8080` work?

我本地启动 但是代理之后无效

**Comment by K41t0uK1dd0** [comment]
试了试，无论是node还是npx都不行。
![image](https://user-images.githubusercontent.com/22808988/132055370-127dd562-e7dd-4eed-9e5e-291e62c7570d.png)

**Comment by KiriTowaha** [comment]
初步推斷係應該係機率性問題。
如果不是的話就是端口被佔用（未確定）
防火牆已經確認有打開。

**Comment by xiaopebaka** [comment]
一直都可以的 今天不知道为啥 我也出现这个问题了  奇怪

**Comment by zkzipoo** [comment]
ping music.163.com 之后是什么IP？有把这个ip放到host里面么

**Comment by valleyzhx** [comment]
我今天遇到同样的问题。最后发现是防火墙的设置。

**Comment by zougn** [comment]
> 我今天遇到同样的问题。最后发现是防火墙的设置。
怎么弄好的

**Comment by zougn** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 80 }
这个问题找到了吗

**Comment by RayneScofield** [comment]
> > Error: connect ECONNREFUSED 127.0.0.1:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 80 }
> > 这个问题找到了吗

怎么解决的，我也是这个问题？

**Comment by RayneScofield** [comment]
> 我今天遇到同样的问题。最后发现是防火墙的设置。

防火墙怎么设置？
