### ISSUE TITLE
请问正常使用中突然报错重开显示TUNNEL - music.163.com:443

### ISSUE THREAD

**Issue by kk748548942** [nondanee/UnblockNeteaseMusic#795]
![image](https://user-images.githubusercontent.com/96098569/145929890-97587e8f-6ab0-4fb2-97b5-8d8fb17cd22e.png)
如图

**Comment by TDSofTM** [comment]
同问，今天上午正常用，中午也遇到这情况了

**Comment by ghost** [comment]
同问 现在无法正常播放

**Comment by not-all** [comment]
https://github.com/nondanee/UnblockNeteaseMusic/issues/85 按照这个可以解决

**Comment by Cccc-ll** [comment]
> #85按照这个可以解决
你好，linux客户端生成证书替换后，还是报错

TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
TUNNEL - music.163.com:443
MITM > clientlog.music.163.com

**Comment by not-all** [comment]
> > #85按照这个可以解决
> > 你好，linux客户端生成证书替换后，还是报错
> 
> TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 MITM > clientlog.music.163.com

添加HTTPS代理端口了吗

**Comment by Cccc-ll** [comment]
> > > #85 按照这个可以解决
> > > 你好，linux客户端生成证书替换后，还是报错
> > 
> > 
> > TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 MITM > clientlog.music.163.com
> 
> 添加HTTPS代理端口号码

没有，之前我是源代码部署的  只开启了一个http端口
node app.js -p 33123

**Comment by not-all** [comment]
> > > > #85 按照这个可以解决
> > > > 你好，linux客户端生成证书替换后，还是报错
> > > 
> > > 
> > > TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 MITM > clientlog.music.163.com
> > 
> > 
> > 添加HTTPS代理端口号码
> 
> 没有，之前我是源代码部署的 只开启了一个http端口 node app.js -p 33123

添加HTTPS代理试试 node app.js -p 33123:33124 这样的

**Comment by Cccc-ll** [comment]
> > > > > #85 按照这个可以解决
> > > > > 你好，linux客户端生成证书替换后，还是报错
> > > > 
> > > > 
> > > > TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 MITM > clientlog.music.163.com
> > > 
> > > 
> > > 添加HTTPS代理端口号码
> > 
> > 
> > 没有，之前我是源代码部署的 只开启了一个http端口 node app.js -p 33123
> 
> 添加HTTPS代理试试 node app.js -p 33123:33124 这样的

请问一下，两个端口的话   网易代理配置 怎么设置呢

网易客户端只有 服务器+端口

**Comment by not-all** [comment]
> > > > > > #85 按照这个可以解决
> > > > > > 你好，linux客户端生成证书替换后，还是报错
> > > > > 
> > > > > 
> > > > > TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 MITM > clientlog.music.163.com
> > > > 
> > > > 
> > > > 添加HTTPS代理端口号码
> > > 
> > > 
> > > 没有，之前我是源代码部署的 只开启了一个http端口 node app.js -p 33123
> > 
> > 
> > 添加HTTPS代理试试 node app.js -p 33123:33124 这样的
> 
> 请问一下，两个端口的话 网易代理配置 怎么设置呢
> 
> 网易客户端只有 服务器+端口

网易客户端还按原来的配置就行

**Comment by Cccc-ll** [comment]
> 网易客户端还按原来的配置就行

直接走http的端口33123吗  不用配置https 33124？

**Comment by not-all** [comment]
> > 网易客户端还按原来的配置就行
> 
> 直接走http的端口33123吗 不用配置https 33124？
对

**Comment by XianyuOne** [comment]
> > > > > #85 按照这个可以解决
> > > > > 你好，linux 客户端生成证书替换后，还是报错
> > > > 
> > > > 
> > > > TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 MITM > clientlog.music.163.com
> > > 
> > > 
> > > 添加 HTTPS 代理端口号码
> > 
> > 
> > 没有，之前我是源代码部署的 只开启了一个 http 端口 node app.js -p 33123
> 
> 添加 HTTPS 代理试试 node app.js -p 33123:33124 这样的

请问一下，node用这个代码可以使用，但pm2为什么就不可以（我需要让它在window后台运行）
代码：
 pm2 start app.js -p 8080:8081
Log：
 address: '::',
0|app      |   port: 8080
0|app      | }
0|app      | Error: listen EADDRINUSE: address already in use :::8080
0|app      |     at Server.setupListenHandle [as _listen2] (net.js:1318:16)
0|app      |     at listenInCluster (net.js:1366:12)
0|app      |     at Server.listen (net.js:1452:7)
0|app      |     at D:\Program\UnblockNeteaseMusic-0.25.3\src\app.js:83:27
0|app      |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
0|app      |   code: 'EADDRINUSE',
0|app      |   errno: -4091,
0|app      |   syscall: 'listen',
0|app      |   address: '::',
0|app      |   port: 8080
0|app      | }

**Comment by jingouwangzi** [comment]
windows已解决，谢谢！请问群晖的docker上能解决吗？

**Comment by kk748548942** [comment]
问题已解决，感谢大佬们

**Comment by Cccc-ll** [comment]
> > > 网易客户端还原来的配置就行
> > 
> > 
> > 直接走http的端口33123吗不用配置https 33124？
> > 对

3Q，按照您的方法，已解决！！！

**Comment by silveryvoid** [comment]
> > > > > #85 按照这个可以解决
> > > > > 你好，linux客户端生成证书替换后，还是报错
> > > > 
> > > > 
> > > > TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 TUNNEL - music.163.com:443 MITM > clientlog.music.163.com
> > > 
> > > 
> > > 添加HTTPS代理端口号码
> > 
> > 
> > 没有，之前我是源代码部署的 只开启了一个http端口 node app.js -p 33123
> 
> 添加HTTPS代理试试 node app.js -p 33123:33124 这样的

现在不行，网络连接错误，还有什么办法吗
